### ISSUE TITLE
Hi rzel100.

### ISSUE THREAD

**Issue by Jef1999** [rzel100/tweezel#4]
I know I'm not supposed to ask a question here, but this is the only place I know you are, don't you have the discord group anymore? 

I went looking for your "tweezel" app in the play store and couldn't find it anymore, it seems like it was removed, now I don't know where to create my games, what happened? What happened to the discord group?

I downloaded these files, but I don't know what to do, I enter "index.html" but it doesn't show anything. I don't know how to do this, could you explain how I make this work so I can create my games again?

If possible, put the old or new "tweezel" on the Google play store.

**Comment by rzel100** [comment]
Hello Jef.

Yes. The TweezeL on play store get removed. Because I never do updates on there so it get removed. Since developing to android platform require good device to do so, I am unable to.

And for the discord, It was deserted. Nothing in there. So it is better to delete the discord group.

To use TweezeL you just need to click this link below. It goes to latest TweezeL build on github pages.
- [Github Pages](https://rzel100.github.io/tweezel-web/)

And I will not re-upload TweezeL to play store since it require so much stuff to do so and also I need to pay some fees if I want to do it.
